### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zyantific/remodel#1]
I would like to point out that an identifier like "[`_REMODEL_PLATFORM_HPP_`](https://github.com/zyantific/remodel/blob/1b868594231a7c2f883ea5f8806816ea26e67131/include/Platform.hpp#L24)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by athre0z** [comment]
Whoops, yep, I forgot about that one, thanks!

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/zyantific/remodel/commit/3f07afa41f4bb4b776db54277eea94b3671882ba).
