### ISSUE TITLE
Problem using remodel

### ISSUE THREAD

**Issue by michaelpittino** [zyantific/remodel#2]
Hello! First of all I have to say that this looks really cool and I'd like to use it but I fail at it.
This is my attempt:

```
class Ped : public remodel::ClassWrapper
{
    REMODEL_WRAPPER(Ped)

public:

    remodel::Field<float> health{ this, 0x540 };

};
```

```
DWORD dwPlayerAddr = *(DWORD*) 0xB6F5F0; // Pointer to Player class

auto player = remodel::wrapper_cast<Ped>(dwPlayerAddr);

Print("Player addr: 0x%x", dwPlayerAddr);
Print("Player Health: %f", player->health);
```

This just outputs 0.00000 as player health while this works:
`*(float*) (dwPlayerAddr + 0x540) // outputs 60.00000`

Did I make anything wrong here?

Best regards

**Comment by athre0z** [comment]
I think that might be related to the var-arg `Print` function you are using there. remodel works by proxifying access to data and `Field` implements implicit conversion to whatever type you pass it. However, as this is a var-arg function, the compiler does not perform any form of implicit conversion and passes the proxy object. Just do a `static_cast` to `float` when passing proxies to var-args functions and you should be good.

**Comment by michaelpittino** [comment]
Works like a charm!
Many thanks :)
